AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: My Basic Lambda Functions

Resources:
  FirstLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: sam_appli/
      Handler: app.lambda_handler
      Runtime: python3.9
      Timeout: 800
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt MySqs.Arn
        FileUpload:
          Type: S3
          Properties:
            Bucket: !Ref MyBucket
            Events: s3:ObjectCreated:*
      Policies:
        - S3ReadPolicy:
            BucketName: missioncsvbucket

      Environment:
        Variables:
          SECOND_QUEUE_ARN: !GetAtt MySecondSqs.Arn
          SECOND_QUEUE_URL: !Ref MySecondSqs

  SecondLambda:
    Type: 'AWS::Serverless::Function'  # Define a new Lambda function
    Properties:
      CodeUri: sam_appli/
      Handler: app.lambda_handler_second  # Point to the second Lambda handler
      Runtime: python3.9
      Timeout: 800
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt MySecondSqs.Arn  # Link the second Lambda to the second SQS queue
      Environment:
        Variables:
          SECOND_QUEUE_URL: !Ref MySecondSqs





  MySqs:
    Type: 'AWS::SQS::Queue'
    Properties:
        QueueName: Queue_1
        VisibilityTimeout: 800


  MySecondSqs:
    Type: 'AWS::SQS::Queue'
    Properties:
      QueueName: Queue_2
      VisibilityTimeout: 800

  MyBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: missioncsvbucket











