version = 0.1
[default.deploy.parameters]
stack_name = "mission-csv"
resolve_s3 = true
s3_prefix = "mission-csv"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
disable_rollback = true
image_repositories = []
